### ISSUE TITLE
拖拽排序部门

### ISSUE THREAD

**Issue by zxz054321** [myzaker/colleague#10]
实现部门列表页的拖拽排序

1. 给部门表增加 sort 字段保存顺序
2. 可在`Api\DepartmentController`增加一个方法，用于保存排序

文档
https://github.com/SortableJS/Vue.Draggable

开发版CDN
`<script src="//cdn.bootcss.com/Vue.Draggable/2.14.1/vuedraggable.js"></script>`

生产版CDN
`<script src="//cdn.bootcss.com/Vue.Draggable/2.14.1/vuedraggable.min.js"></script>`

**Comment by zxz054321** [comment]
@170cmcurry 有没有发现在firefox下拖拽，会打开新标签页？

**Comment by 170cmcurry** [comment]
@zxz054321 不知道啊，只再chrome测试过，我现在下firefox试试

**Comment by 170cmcurry** [comment]
@zxz054321 刚刚试过，firefox没问题

**Comment by zxz054321** [comment]
Fixed
